### ISSUE TITLE
Stop insulting engineering. Mechanical Engineering is the ONLY Engineering

### ISSUE THREAD

**Issue by ghost** [NFRage/nfrage#1]
There is no such this as "reverse engineering". That is the stupidest and most pathetic lie ever. Stop being disrespectful & insulting to Engineering. You know nothing about what Engineering entails. Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with clowns sitting behind a keyboard and decoding/programming/deciphering etc. Software dev is easy and for kids. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). Quit making false claims against engineering . And stop being disrespectful to real engineers (Mechanical Engineering is the ONLY Engineering, PERIOD).

**Comment by vertver** [comment]
Ok man don't care
